//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseArchitectAutoRefresh.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int refreshInterval {
            get {
                return ((int)(this["refreshInterval"]));
            }
            set {
                this["refreshInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ht_")]
        public string tablePrefix {
            get {
                return ((string)(this["tablePrefix"]));
            }
            set {
                this["tablePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showAlertFirst {
            get {
                return ((bool)(this["showAlertFirst"]));
            }
            set {
                this["showAlertFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>t_attribute</string>
  <string>t_attributetag</string>
  <string>t_connector</string>
  <string>t_diagram</string>
  <string>t_diagramlinks</string>
  <string>t_diagramobjects</string>
  <string>t_object</string>
  <string>t_operation</string>
  <string>t_operationparams</string>
  <string>t_package</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection mappedTables {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["mappedTables"]));
            }
            set {
                this["mappedTables"] = value;
            }
        }
    }
}
